Add TableComponent WIP specs
BuoySoftware/anchor_view_components pull request #33
Opened 2023-08-23 16:41 UTC by tute

Supersedes https://github.com/BuoySoftware/anchor_view_components/pull/9

TODO: reference properly the local asset in the `bg-[url('assets/sort_handle.svg')]` Tailwind class name.

2023-08-23 16:51 UTC, tysongach commented
@tute Can we please add a component preview?

2023-08-23 19:15 UTC, tute commented
And also I get in the preview
``Asset `sort_handle.svg` was not declared to be precompiled in production.
Declare links to your assets in `app/assets/config/manifest.js`.

  //= link sort_handle.svg

and restart your server```
I'll ask for yours or @Simonpedro's help on that one please.

2023-08-23 20:31 UTC, Simonpedro commented on app/assets/images/sort_handle.svg
Will this asset be available when the gem is installed in Infirmary or others?

2023-08-23 20:31 UTC, Simonpedro approved these changes

2023-08-23 20:44 UTC, tute commented on app/assets/images/sort_handle.svg
Yes, double checked against a local installation without the file in the host app.

2023-08-23 21:20 UTC, tysongach commented on app/assets/images/sort_handle.svg
I’d love to keep this asset in line with the other icons we provide…

1. Can we move this into the `images/icons` directory?
2. Rename it to `sort-handle.svg` to be consistently named
3. Where was this icon sourced from? Other icons have come from https://iconoir.com - can we use one from there if this one isn’t?
4. I noticed it is sized 16×16 whereas our other icons are 24×24 - can this one be 24×24? I’ve always gotten a ton of value out of an icon system that carry a consistent sizing constraint.

2023-08-23 21:20 UTC, tysongach commented on app/components/anchor/table_component.html.erb
> +    @data.each do |model| %>
We have a preference for using methods instead of instance variables - can we add an attribute accessor for `@data`?

2023-08-23 21:20 UTC, tysongach commented on app/components/anchor/table_component.rb
> +    private
I believe this `private` can move all the way up, as [instance methods are available in the template](https://viewcomponent.org/viewcomponents-at-github.html#most-viewcomponent-instance-methods-can-be-private).

2023-08-23 21:20 UTC, tysongach commented on app/components/anchor/table_component.html.erb
> +        class: "border-b hover:bg-grey-10 hover:cursor-pointer focus-within:bg-grey-10",
If possible, the class`hover:cursor-pointer` should only be applied if the row is linked. As it is now, a cursor is shown which makes it look like it’s a clickable link, even if it’s not.

2023-08-23 21:24 UTC, tysongach requested changes
I think our table row linking hack got mixed up somewhere along the line.

Right now, every cell’s text is wrapped in a link, but what we need is for only the first cell to have its text wrapped:

```diff
 <tbody>
   <tr>
     <td>
       <a href="#a_link/1">1</a>
       <a aria-hidden="true" tabindex="-1" href="#a_link/1"></a>
     </td>

     <td>
-      <a href="#a_link/1">Name 1</a>
+      Name 1
       <a aria-hidden="true" tabindex="-1" href="#a_link/1"></a>
     </td>
   </tr>
 </tbody>
```

We should probably write a test specifically for this as it’s really important for a11y.

2023-08-24 11:51 UTC, tute commented on README.md
> +- Launch `rails server` in `demo/`
Now it works without compiling, I don't know why it wasn't finding `application.css` (I removed it from my `build/` directory and still works). Cool, will update as suggested!

2023-08-24 11:54 UTC, tute commented on README.md
> +- Run `yarn build:css` in the root of the project
README updated 4587146

2023-08-24 12:12 UTC, tute commented on app/assets/images/sort_handle.svg
Yes to all! I took it from: https://github.com/BuoySoftware/anchor-ui/blob/main/packages/components/table/src/sort_handle.svg

I now picked this one:
<img width="710" alt="Screenshot 2023-08-24 at 09 08 57" src="https://github.com/BuoySoftware/anchor_view_components/assets/54260/c6a90777-89c4-4e9f-b083-9425f6fb09b3">

It looks a bit different, should I resize back to make it smaller? ok to pick that one?

What was strange is I couldn't render it in Preview until I did my commands as spelled before, I don't know what's different.

2023-08-24 12:44 UTC, tysongach commented on README.md
> +- Launch `rails server` in `demo/`
`bin/dev` runs the [`Procfile.dev`](https://github.com/BuoySoftware/anchor_view_components/blob/main/demo/Procfile.dev), which includes a command to build the CSS. I’m guessing `rails server` wasn’t triggering that build and so `application.css` didn’t exist.

2023-08-24 13:57 UTC, tute commented on app/assets/images/sort_handle.svg
Right, we used inline rendering to work around that in https://github.com/BuoySoftware/anchor_view_components/pull/27.

2023-08-24 14:39 UTC, tute commented on app/components/anchor/table_component.html.erb
> +    @data.each do |model| %>
Yep! attr_reader rather than ivars as of a713ba7

2023-08-24 14:41 UTC, tute commented on app/components/anchor/table_component.rb
> +    private
Pushed `private` all the way up in bf80db6. That made me think we may as well not use it?

2023-08-24 14:55 UTC, tute commented on app/components/anchor/table_component.html.erb
> +        class: "border-b hover:bg-grey-10 hover:cursor-pointer focus-within:bg-grey-10",
Right, fixed the classes with fda65bf

2023-08-24 15:26 UTC, tysongach commented on app/assets/images/sort_handle.svg
<img width="866" alt="Screenshot 2023-08-24 at 10 26 55" src="https://github.com/BuoySoftware/anchor_view_components/assets/903327/7b1a28f4-5112-4570-b5e1-8767be60f84f">

2023-08-24 15:37 UTC, tysongach commented on app/assets/images/sort_handle.svg
Actually - there’s no need to switch. I just swapped it again.

It’s the same icon, visually speaking, but now sourced from Iconoir so it is consistently built like our other system icons.
<img width="835" alt="Screenshot 2023-08-24 at 10 37 18" src="https://github.com/BuoySoftware/anchor_view_components/assets/903327/da020aec-6b80-4771-9a81-856520529e55">

2023-08-24 15:39 UTC, dgalarza commented on app/assets/images/sort_handle.svg
🚢

2023-08-25 12:09 UTC, tysongach reviewed
This is looking good, Tute! The link markup is working as expected. 

I’m getting an `ActionView::Template::Error` on the `playground` and `sortable` previews now.

2023-08-25 14:53 UTC, tute commented
True, fixed @tysongach!

2023-08-25 15:07 UTC, merged